apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq01
spec:
  version: 9.3.3.0-r1
  license:
    accept: true
    license: L-YBXJ-ADJNSM
    use: NonProduction
  web:
    enabled: true
  queueManager:
    image: image-registry.openshift-image-registry.svc:5000/mq01-ci/mq01:0.0.1
    name: "MQ01"
    storage:
      queueManager:
        type: ephemeral
  template:
    pod:
      containers:
       - name: qmgr
         env:
         - name: MQSNOAUT
           value: "yes"
